# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6c222e55994ad8a1e1177fb13f201a1cd74a0ed7a35146a6d7814e823d194223010c07a69c8ac0644ddaa2aebc99d9aad365e3ab32a2f094b77eab667763308

test:
  secret_key_base: bef098fff7c022248469de9c724c7cbd45b4f53f58dfc218a2ede8c46b9e214c48fed38db7f029756029841889bcea77bc07b31b7edfaa9d0bb0abde2cbd2798

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
